server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/accounts
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: pass@123
  h2:
    console:
      enabled: true
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
