spring:
  datasource:
    url: jdbc:h2:mem:crp
    username: root
    password: pass@123
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
